### ISSUE TITLE
Editto di Anne

### ISSUE THREAD

**Issue by mzanella** [Polpetta/TOSNotes#3]
L'editto di Anne (si scrive Anne non Ann) è del 1710 non 1740 fonte [Wikipedia](https://en.wikipedia.org/wiki/Statute_of_Anne)

**Comment by Polpetta** [comment]
In che lezione e'? 😊

**Comment by mzanella** [comment]
6-10-15 sezione "Inghilterra e Copyright"


Il 3 feb 2017 5:35 PM, "Davide Polonio" <notifications@github.com> ha
scritto:
